import Link from 'next/link';
import React from 'react';
export const metadata = {
  title: "Create About App",
  description: "Generated by create About app",
  };

const layout = ({children}) => {
    return (
        <div className='p-6'>
            <nav>
        <ul className="flex space-x-5">
          <li><Link href="/about/mission">Mission</Link></li>
          <li><Link href="/about/vision">Vision</Link></li>
        </ul>
      </nav>
      <hr className=" border-black"></hr>
        {children}
            
        </div>
    );
};

export default layout;